site_name: LGSVL Simulator

repo_url: https://github.com/lgsvl/simulator
site_author: LG Silicon Valley Lab
site_description: Automotive vehicle simulator from LG Silicon Valley Lab
site_url: https://www.lgsvlsimulator.com

edit_uri: edit/master/Docs/

docs_dir: docs

theme:
  name: null
  custom_dir: 'theme/' # readthedocs modified

copyright: Copyright &copy; 2019 LG Electronics Inc.

google_analytics: ['UA-130546445-1','lgsvlsimulator.com/docs']

nav:
- 'Home': 'index.md'
- 'Quick start':
  - 'Getting started': 'getting-started.md'
  - 'Build instructions': 'build-instructions.md'
  - 'Keyboard shortcuts': 'keyboard-shortcuts.md'
  - 'Ground truth obstacles': 'perception-ground-truth.md'
- 'Integration with AD':
  - 'Running with Autoware': 'autoware-instructions.md'
  - 'Running with Apollo 3.5': 'apollo3-5-instructions.md'
  - 'Running with Apollo 3.0': 'apollo-instructions.md'
- 'Python API':
  - 'Python API Guide': 'python-api.md'
  - 'Python API Quickstart Examples': 'api-quickstart-descriptions.md'
  - 'Python API Use Case Examples': 'api-example-descriptions.md'
  - 'How to Run a Scenario' : 'api-how-to-run-scenario.md'
- 'Tutorials':
  - 'Map Annotation': 'map-annotation.md'
  - 'Reinforcement Learning with OpenAI Gym': 'openai-gym.md'
  - 'Deep Learning Lane Following Model': 'lane-following.md'
  - 'How to create a simple ROS2-based AD stack': 'create-ros2-ad-stack.md'
  - 'How to add a new ego vehicle': 'add-new-ego-vehicle.md'
  - 'NPC Map Navigation': 'npc-map-navigation.md'
- 'Support':
  - 'FAQ': 'faq.md'
  - 'Contributing': 'contributing.md'
